### PR TITLE
Migrate to use `ChrisCarini/intellij-platform-plugin-verifier-action`.

### PR DESCRIPTION
**Pull request by ChrisCarini**
Please see docs here for more details: https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action/blob/master/README.md

### CODE REVIEW

**Comment by ChrisCarini** [comment]
@jensstockhausen - gentle reminder on this PR.

**Comment by ChrisCarini** [comment]
@jensstockhausen - gentle reminder again on this PR.

**Comment by jensstockhausen** [comment]
Hi @ChrisCarini, 
just saw your request, can you give me a little bit more information on this.
Is the thepieterdc/intellij-plugin-verifier-action discontinued? 
I'm not keen on accepting merge requests if I don't know the reason.

**Comment by ChrisCarini** [comment]
Hi @jensstockhausen - no problem, happy to provide more detail!

The `ChrisCarini/intellij-platform-plugin-verifier-action` action provides more flexibility out-of-the-box compared to `thepieterdc/intellij-plugin-verifier-action` - for example,

1. you can test against more than just `IntelliJ` IDE (See [this direct link to the respective section of the docs](https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action#ide-versions) for more info)
2. By default we use the latest version of the platform verifier (but, unlike `thepieterdc/intellij-plugin-verifier-action`, you are able to pin to a specific version if you need)
3. By default, you do not need to specify your plugin location, as we will try to automatically detect any zip files in the build distribution directory (**Note:** I left the existing logic in this workflow file in this PR to find the zip file just in case there were other ZIPs that matched in that directory - please feel free to remove this line (line 29) and things should work as expected so long as this repo only produces JetBrains plugin zip artifacts there.)
4. Is used much more broadly ([>520 as of writing](https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action/network/dependents), compared to [11, including your repo here](https://github.com/thepieterdc/intellij-plugin-verifier-action/network/dependents)) by IntelliJ plugins using GitHub Actions
5. You are also able to [exclude failure levels from the verifier if you so choose to do so](https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action#failure-levels) based on a configuration option

Let me know if you have further questions or concerns - I'd be happy to help / address them!

Cheers,
Chris

**Review by jensstockhausen — APPROVED** [review]

**Pull request merged**
